### ISSUE TITLE
Help needed! Carousel rendering slides 3x the length of array

### ISSUE THREAD

**Issue by danishgrappus** [vadymshymko/react-simply-carousel#123]
**Describe the bug**
I am getting slides 3 times the length of array.
Eg: If my array has 2 items, it renders 6 divs. If array has 7 items, then 21 divs.

Attaching a codesandbox link for clarity: https://codesandbox.io/s/react-simply-carousel-demo-forked-zspf45?file=/src/index.js

**Expected behavior**
Number of slides should be equal to length of array

**Screenshots**

**Desktop (please complete the following information):**

Windows 10, Chrome

Please help!!

**Comment by vadymshymko** [comment]
Hello @danishgrappus . What you describe is not a bug. This is a feature of the implementation of the infinite scroll mode. If you want to get rid of duplicate slides, you can disable the infinite scroll mod (pass `infinite={false}`)
