### ISSUE TITLE
When items to scroll is greater than the actual children, swipe by mouse or touch are malfunctioning

### ISSUE THREAD

**Issue by YaswanthSaiCh** [vadymshymko/react-simply-carousel#167]
> **Description of the Bug**

When we set **itemsToScroll** and the items in the list are **less than that number**, then when we drag the list to right or left, the list is moving way more and if we move them to extremes they are disappearing.

> **To Reproduce**

I am providing a link of codesandbox which contains the same configuration I did in my project, you can run the sandbox to reproduce the issue
[Click Here](https://codesandbox.io/s/serverless-glade-dnnid5) to get to the sandbox

> **Expected behavior**

 What I think would be the ideal scenario is that if all the list items are visible then the drag functionality should be disabled and it should be the same when the items to scroll is greater than the actual list of items.

>**Screenshot of the issue**

![image](https://github.com/vadymshymko/react-simply-carousel/assets/52790859/820f2f92-4ebd-4d64-b623-c4c051f520f3)

**Comment by beardsleym** [comment]
This could be a similar issue to when ` array length of items to scroll === itemsToShow`, the carousel is not able to scroll with mouse, only by clicking the `dotsNav`

See codesandbox example https://codesandbox.io/s/react-simply-carousel-demo-forked-57cw5l

> Steps to reproduce from the original demo
> - change children item `width to '80vw'`
> - change `itemsToShow={2}`
