### ISSUE TITLE
next.js: ReferenceError: document is not defined

### ISSUE THREAD

**Issue by JannikZed** [vadymshymko/react-simply-carousel#19]
**Describe the bug**
I'm using next.js 9.4 and was trying to use your library, as you are describing it with "SSR Support". Unfortunately the compilation fails with: ReferenceError: document is not defined

**Comment by vadshymko** [comment]
> **Describe the bug**
> I'm using next.js 9.4 and was trying to use your library, as you are describing it with "SSR Support". Unfortunately the compilation fails with: ReferenceError: document is not defined

Hey.  Could you please provide the source code for the part of your project that uses react-simply-carousel?

**Comment by vadymshymko** [comment]
> **Describe the bug**
> I'm using next.js 9.4 and was trying to use your library, as you are describing it with "SSR Support". Unfortunately the compilation fails with: ReferenceError: document is not defined

Hey.  Could you please provide the source code for the part of your project that uses react

**Comment by vadymshymko** [comment]
This error occurred due to the style-loader. Fixed in v3.0.0 #26
