### ISSUE TITLE
Responsive Props make no difference

### ISSUE THREAD

**Issue by alex4brandung** [vadymshymko/react-simply-carousel#205]
**Describe the bug**
Trying the slider look on tablet the same like mobile.

**To Reproduce**

1. Go to codesandbox example
2. Add the following props

```js

          responsiveProps={[
            {
              itemsToShow: 2,
              itemsToScroll: 1,
              minWidth: 768,
            },
          ]}
```

**Expected behavior**
I see 3 items same as mobile.

**Screenshots**
Mobile:
![Bildschirmfoto 2023-12-19 um 12 47 16](https://github.com/vadymshymko/react-simply-carousel/assets/137274125/be595d3b-f0fd-4df8-892d-caaf9b764650)

Tablet:
![Bildschirmfoto 2023-12-19 um 12 46 49](https://github.com/vadymshymko/react-simply-carousel/assets/137274125/154227e0-9e59-4021-afa0-c526861059dc)

**Desktop:**

- OS: MacOS
- Browser chrome
- Version 120

**Comment by vadymshymko** [comment]
@alex4brandung hello. please add a link to the example

**Comment by alex4brandung** [comment]
this can be closed... The problem was that I didnt really realize that the entire container with the slides has a max width of 600px...
