### ISSUE TITLE
Click not working in carousel items after swipe

### ISSUE THREAD

**Issue by camilacnery** [vadymshymko/react-simply-carousel#212]
**Describe the bug**
When using the swipe behavior, if you have clickable items inside the carousel eventually the click stops working.

**To Reproduce**
1. Swipe carousel item
2. Try to click it
3. Repeat until the click will eventually stop working

[CodeSandbox](https://codesandbox.io/p/sandbox/react-simply-carousel-demo-forked-gsxclh?file=%2Fsrc%2Findex.js%3A81%2C41-81%2C42) - this is basically the same demo code available in this repo, just adding a click event to the carousel item

**Expected behavior**
Always be able to click on the items after swipe

**Screenshots**
https://github.com/vadymshymko/react-simply-carousel/assets/8807085/c74d4513-f003-42b4-8611-99604634e0d0

I recorded a video showing what happens here. In every swipe I was doing a click, by the end of the video you'll notice the clicks stop working completely.

**Desktop (please complete the following information):**

- OS: MacOS
- Browser: Chrome
- Version: 120

Is there anything I'm doing wrong? Am I missing some setting?

**Comment by html5-ninja** [comment]
exactly the same issue

**Comment by camilacnery** [comment]
Yeah, in my case I need the swipe with mouse behavior to work, so I'm not able to use `disableSwipeByMouse` :(

**Comment by vadymshymko** [comment]
@camilacnery Hello. Thanks for the report and demo. I'll try to fix this problem soon

**Comment by Yaswanth-Adeption** [comment]
Hey @vadymshymko, are you planning to release this bug, actually we are using this carousel in our project and we are also facing the same issue, and we have tried the workaround mentioned by @html5-ninja but that also didnt workout for us. So if you are planning to release this week it will be helpful for us. Otherwise we need to find any other workaround.
These are our configurations for the carousel, if you need
`
<ReactSimplyCarousel
          activeSlideIndex={activeSlideIndex}
          onRequestChange={setActiveSlideIndex}
          itemsToScroll={isMobile ? 1 : 3}
          infinite={false}
          disableSwipeByMouse={true}
          disableSwipeByTouch={
            (isMobile ? 1 : 3) >= getList?.length
          }
          forwardBtnProps={{
            className: 'carousal-btn fwd',
            children: <span>{}</span>
          }}
          backwardBtnProps={{
            className: 'carousal-btn bcd',
            children: <span>{}</span>
          }}
          speed={400}
          easing="linear"
        >`

Feel free to ask anything if you need :)

**Comment by vadymshymko** [comment]
@camilacnery @html5-ninja @Yaswanth-Adeption please try v9.1.2

**Comment by Yaswanth-Adeption** [comment]
Hey @vadymshymko  thank you for your response, I will update the package and check the issue and will update you in some time
