### ISSUE TITLE
Responsiveness behavior is not working

### ISSUE THREAD

**Issue by vivektak** [vadymshymko/react-simply-carousel#37]
**Describe the bug**
When trying to check it in the mobile, responsiveness is missing, even after making use of responsiveProps

**To Reproduce**
<Carousel
          updateOnItemClick
          containerProps={{
            style: {
              width: '100%',
              justifyContent: 'space-between',
            },
          }}
          responsiveProps={[{minWidth: 768, maxWidth: 992, itemsToShow: 3}, {maxWidth: 767, itemsToShow: 1}]}
          activeSlideIndex={activeSlide}
          onRequestChange={setActiveSlide}
          disableNavIfEdgeVisible={true}
          disableNavIfEdgeActive={true}
          infinite={false}
          forwardBtnProps={{
            children: '>',
            className: classes.forwardButton,
          }}
          backwardBtnProps={{
            children: '<',
            className: classes.backwardButton,
          }}
          itemsToShow={2}
          speed={400}
        >
         <div>Item</div>
        </Carousel>

**Expected behavior**
Should work fine for mobile devices

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vadymshymko** [comment]
@vivektak I tried and it works well: [https://codesandbox.io/s/react-simply-carousel-demo-forked-lowri?file=/src/index.js](https://codesandbox.io/s/react-simply-carousel-demo-forked-lowri?file=/src/index.js)
