### ISSUE TITLE
When `inifinite=true` the Carousel Items are duplicated 3 times.

### ISSUE THREAD

**Issue by iampava** [vadymshymko/react-simply-carousel#44]
**Describe the bug**
When `infinite=true`, the carousel items are duplicated 3 times.

**To Reproduce**
1. Create a Carousel (you can use the code in the `README.md`
2. Open DevTools and look at the HTML

Sandbox example: https://codesandbox.io/s/agitated-carlos-z6qzvs

**Expected behavior**
I'd expect that items don't need to be duplicated, and the `infinite` feature is achieved by shuffling items around.

**Comment by vadymshymko** [comment]
Hello @iampava. I am very happy that you are using (or at least trying) my carousel component. In response to your appeal, I have to inform you that duplication is not a bug at the moment - it is rather a flaw in the current implementation of the component. I'm thinking about how to get rid of this, but I can't say anything specific about the timing yet.

I hope my answer will be of some use to you

**Comment by iampava** [comment]
Hey and thanks for the reply.

I think I've managed to get implement what I'm looking for by using `infinite=false` and then having some custom logic that changes the slide, if we reach either the beginning or the end.

```jsx
const Carousel = (items: any[]) => {
  // Adding the last element before the first,
  // and the first element after the last, so that when we 
  // reach the end of the carousel, the buttons are not disabled.
  items = [
    items[items.length - 1],
    ...items,
    items[0]
  ];

  const [activeSlideIndex, setActiveSlideIndex] = useState(1);
  const onSlideChange = (slideIndex: number) => {
    if (slideIndex === 0) {
      // The first slide is actually the last
      // So let's jump towards the end of the Array, 
      // so the user can keep navigating backward.
      slideIndex = items.length - 2;
    } else if (slideIndex === items.length - 1) {
      // The last slide is actually the first.
      // So, let's jump towards the beginning of the Array,
      // so the user can keep navigating forward.
      slideIndex = 1;
    }

    setActiveSlideIndex(slideIndex);
  }


  return (
    <ReactSimplyCarousel
      infinite={false}
      itemsToShow={1}
      itemsToScroll={1}
      activeSlideIndex={activeSlideIndex}
      onRequestChange={onSlideChange}
    >
      {items.map((item) => (
        <CarouselItem item={item} />
      ))}
    </ReactSimplyCarousel>
  )
}
```

I just tested it and it seems to work. What do you think?

**Comment by iampava** [comment]
Perfect! My speed is `0` 😁

**Comment by vadymshymko** [comment]
> Perfect! My speed is `0` grin

Also, while examining your example, I found that the navigation buttons do not call the onRequestChange prop if the first or last slide is active (in this case, the disableNavIfEdgeVisible and disableNavIfEdgeActive props are set to false). This is a bug, fixing which will allow you to use the solution you suggested without modifying items. The final code would look something like this:

```
export default function App(items) {
  const [activeSlideIndex, setActiveSlideIndex] = useState(0);

  const onSlideChange = (slideIndex: number) => {
    if (activeSlideIndex === 0 && slideIndex === 0) {
      slideIndex = items.length - 1;
    } else if (
      activeSlideIndex === items.length - 1 &&
      slideIndex === items.length - 1
    ) {
      slideIndex = 0;
    }

    setActiveSlideIndex(slideIndex);
  };

  return (
    <div className="App">
      <Carousel
        activeSlideIndex={activeSlideIndex}
        onRequestChange={onSlideChange}
        infinite={false}
        itemsToShow={1}
        itemsToScroll={1}
        disableNavIfEdgeVisible={false}
        disableNavIfEdgeActive={false}
      >
        {items.map((item, index) => (
```

I'll try to fix this soon

**Comment by iampava** [comment]
Got it. Thanks a lot 🙌
