### ISSUE TITLE
Recent changes to `max-width` property mean that the first item won't display without JS

### ISSUE THREAD

**Issue by iampava** [vadymshymko/react-simply-carousel#47]
**Describe the bug**
Recently I updated to the latest version and discovered the first item in the Carousel doesn't render without JS. I think it's because of this `max-width: 0` which only gets changed once JS runs.

<img width="732" alt="image" src="https://user-images.githubusercontent.com/11327761/172728034-83d1258e-019b-4211-a069-3d083dcd4d9f.png">

This is important to me because I'm focusing on performance, so I want to show the user something without having to wait for JS to load, parse and run.

**To Reproduce**
1. Create a Carousel
2. Disable JavaScript in the page and refresh

**Expected behavior**
I expect to see the first item in the carousel, rendered.

**Comment by vadymshymko** [comment]
@iampava Can be fixed with a new prop `showSlidesBeforeInit`. It was added in [v8.2.0](https://www.npmjs.com/package/react-simply-carousel/v/8.2.0).

**Comment by iampava** [comment]
Interesting... I wonder why it needs such a property, I'd expect it to work by default. Is there a downside to having this enabled at all times?

**Comment by vadymshymko** [comment]
> Interesting... I wonder why it needs such a property, I'd expect it to work by default. Is there a downside to having this enabled at all times?

Yes. Disadvantage small but present - when enabled, you may notice flickering of content on initial render
