### ISSUE TITLE
Stopped working after text being selected

### ISSUE THREAD

**Issue by Frastio10** [vadymshymko/react-simply-carousel#53]
**Describe the bug**
I tried both examples to my project. There is a problem after some text being selected inside the slide the carousel stopped working, even the dots didn't do anything when I clicked it. I had to refresh the page in order to make it back to work. But, when I accidentally selected some text, it will stop working again.

I thought the issue was on my browser but even if I changed it to Edge and Chrome this problem still remains.

**To Reproduce**

1. Open the demo on Codepen or run it on local
2. Select the text on the middle
3. Try to click the dots or swipe the slide

**Expected behavior**
Still works when being selected/unselected

**Screenshots**
![image](https://user-images.githubusercontent.com/43699753/175117308-6c345ce4-035b-403d-923e-272c554ac60b.png)

**Desktop (please complete the following information):**

- OS: [e.g. Windows 10]
- Browser [e.g. Chrome, Edge]
- Version [e.g. latest version]

**Comment by vadymshymko** [comment]
Hello @Frastio10 . Thanks for the report. This bug has been fixed in #54. The new version will be published as soon as possible (within a few hours)

**Comment by vadymshymko** [comment]
Fixed in [v8.3.2](https://github.com/vadymshymko/react-simply-carousel/releases/tag/v8.3.2)

**Comment by Frastio10** [comment]
Thank you so much!
