### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'offsetWidth')

### ISSUE THREAD

**Issue by Tauqeer180** [vadymshymko/react-simply-carousel#56]
**Describe the bug**
Unhandled Runtime Error
TypeError: Cannot read properties of undefined (reading 'offsetWidth')

Call Stack
eval
node_modules\react-simply-carousel\dist\index.esm.js (1:5567)
C
node_modules\react-simply-carousel\dist\index.esm.js (1:7350)
renderWithHooks
node_modules\react-dom\cjs\react-dom.development.js (16141:0)
updateFunctionComponent
node_modules\react-dom\cjs\react-dom.development.js (20313:0)
updateSimpleMemoComponent
node_modules\react-dom\cjs\react-dom.development.js (20151:0)
beginWork
node_modules\react-dom\cjs\react-dom.development.js (22433:0)
HTMLUnknownElement.callCallback
node_modules\react-dom\cjs\react-dom.development.js (4157:0)
HTMLUnknownElement.nrWrapper
/ (1:30750)
Object.invokeGuardedCallbackDev
node_modules\react-dom\cjs\react-dom.development.js (4206:0)
invokeGuardedCallback
node_modules\react-dom\cjs\react-dom.development.js (4270:0)
beginWork$1
node_modules\react-dom\cjs\react-dom.development.js (27243:0)
performUnitOfWork
node_modules\react-dom\cjs\react-dom.development.js (26392:0)
workLoopSync
node_modules\react-dom\cjs\react-dom.development.js (26303:0)
renderRootSync
node_modules\react-dom\cjs\react-dom.development.js (26271:0)
recoverFromConcurrentError
node_modules\react-dom\cjs\react-dom.development.js (25689:0)
performConcurrentWorkOnRoot
node_modules\react-dom\cjs\react-dom.development.js (25589:0)
workLoop
node_modules\scheduler\cjs\scheduler.development.js (266:0)
flushWork
node_modules\scheduler\cjs\scheduler.development.js (239:0)
MessagePort.performWorkUntilDeadline
node_modules\scheduler\cjs\scheduler.development.js (533:0)

**To Reproduce**
react-simply-carousel :8.3.3
Environment NextJS

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/47059409/177024196-d61ffa6a-8338-4a30-98c4-e85dc967bfaa.png)

**Comment by vadymshymko** [comment]
Hello @Tauqeer180 . THNX for the report. Can you provide the source code or maybe a link to the repo?
