### ISSUE TITLE
Cannot read property 'offsetWidth' of undefined

### ISSUE THREAD

**Issue by amrit-codebuckets** [vadymshymko/react-simply-carousel#60]
This issue come multiple times and it breaks the complete page
![Screenshot from 2022-09-18 18-52-26](https://user-images.githubusercontent.com/75237977/190904399-a4a9c062-85cf-4df2-bc55-34f12ee55372.png)

**Comment by vadymshymko** [comment]
Hello @amrit-codebuckets! Thanks for the report. Please provide some of your source code or an example of how you are using react-simply-carousel. This may help to understand what is causing the problem.

**Comment by amrit-codebuckets** [comment]
Hi @vadymshymko, thanks for for the quick reply. I think it was on the older version, I have updated the version and it stared working. You can close this issue
