### ISSUE TITLE
Back Button Navigation Issues

### ISSUE THREAD

**Issue by bantr-ryan** [vadymshymko/react-simply-carousel#61]
**Describe the bug**
***Issue:*** The carousel back button is enabled but clicking it does nothing.

***Long Description:*** There seems to be a bug in the carousel component that is preventing the carousel from navigating to the first set of slides when the following are true:
- `activeSlideIndex` is initially set to a value greater than 0
- `infinite` is false
- `disableNavIfEdgeVisible` is true

In our application, the carousel is used as a sort of navigation tool, where a query parameter could be used to set the initially active slide of the carousel. When the page loads, the carousel renders as expected with the query parameter slide selected. The user is able to navigate forward and backwards (mostly) as expected.

The issue comes when the user tries to navigate to the first slide, or first set of slides containing the first slide. In this instance, there are still a set of slides to navigate into view and the back button is correctly enabled, but if the number of slides to scroll is greater than the number of slides remaining, the carousel does not seem to call the onRequestChange function.

**To Reproduce**
This is the official sandbox linked from this repo. I forked it and changed a few configurations to match how my team is using the carousel.
https://codesandbox.io/s/react-simply-carousel-demo-back-nav-issue-xkoysw?file=/src/index.js

**Expected behavior**
Clicking the back button will navigate the user to the first set of slides.

**Desktop (please complete the following information):**
- OS: Mac Monterey 
- Browser: Latest Chrome

**Smartphone (please complete the following information):**
- Yes, also affecting Android and iPhone

**Screenshots**
In this gif, `itemsToScroll={3}`. When I select the a matchday, the back button no longer works. At the end when you see the mouse over the active back button, I am attempting to click it, and the callback function does not fire. 

![Kapture 2022-11-09 at 17 36 08](https://user-images.githubusercontent.com/88356285/200971891-dd1bd142-5d27-4db6-ab66-d4c3598e9fe9.gif)

**Comment by vadymshymko** [comment]
Hello @bantr-ryan. Thanks for the report! Will be fixed as soon as possible

**Comment by bantr-ryan** [comment]
@vadymshymko Confirming that the fix worked in our application. Thank you for the quick response!!
