### ISSUE TITLE
Stop propagating touch events on mobile when scrolling carousel with a finger

### ISSUE THREAD

**Issue by ssijak** [vadymshymko/react-simply-carousel#80]
**Is your feature request related to a problem? Please describe.**
If carousel is inside a vertically scrolling container, when trying to slide carousel left-right on mobile it will also scroll the container up and down which is not very nice UX

**Describe the solution you'd like**
When carousel captures touch events, prevent propagating them

**Describe alternatives you've considered**
Increase horizontal sensitivity (with a prop) so that left-right touch scroll happen faster, but that would still not fix the core issue. But that could also be a separate feature improvement: prop that configures what percentage of the width of carousel needs to be scrolled for carousel to animate to the new slide

**Comment by vadymshymko** [comment]
Hello @ssijak. Thanks for the report. I think the problem you described can be solved by adding the following props

```
itemsListProps={{
  style: {
    touchAction: "none"
  }
}}
```

I hope this helps. Please let me know

**Comment by ocastaneda82** [comment]
It worked for me!
