### ISSUE TITLE
Stop scroll when you pass infinite as false in responsive mode

### ISSUE THREAD

**Issue by ocastaneda82** [vadymshymko/react-simply-carousel#87]
**When you setup the infinite as false, your responsive scroll stop before you see your last item**

**To Reproduce**
<code> infinite={false} </code>

**Expected behavior**
It would be show all the items, right?

**Comment by vadymshymko** [comment]
Hi, @ocastaneda82 . If I understand the bug correctly, it should be fixed in v8.5.0. Please let me know if this is true

**Comment by vadymshymko** [comment]
> Hi, @ocastaneda82 . If I understand the bug correctly, it should be fixed in v8.5.0. Please let me know if this is true

upd. Try v8.5.1

**Comment by ocastaneda82** [comment]
It is working now!
